#!/bin/sh

export P4JOURNAL=/var/log/perforce/journal
export P4LOG=/var/log/perforce/p4err
export P4ROOT=/mnt/perforce-pga/perforce_depot
export P4PORT=1666

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

. /lib/lsb/init-functions

p4start="p4d -d"
p4stop="p4 admin stop"
p4user=perforce

case "$1" in
  start)
    log_action_begin_msg "Starting Perforce Server"
    daemon -u $p4user -- $p4start;
    ;;

  stop)
    log_action_begin_msg "Stopping Perforce Server"
    daemon -u $p4user -- $p4stop;
    ;;

  restart)
    stop
    start
    ;;

*)
  echo "Usage: /etc/init.d/perforce (start|stop|restart)"
  exit 1
  ;;

esac

exit 0
